Первая итерация дз 9 спринта
Kirill-Prokhorov/java-filmorate pull request #2
Opened 2022-09-18 16:27 UTC by Kirill-Prokhorov

2022-09-18 20:53 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-09-18 20:53 UTC, FanaticFiz commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Кирилл, привет.
Начну с `pom` файла.

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Хорошим тоном будет указание кодировки в properties `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-09-18 20:53 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Советую прочитать про семантическое версионирование, ну а после не стесняйся - смело проставь версию своему новому сервису!

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +package ru.yandex.practicum.filmorate.controllers;
Приди к единому и однообразному именованию пакетов.
Как ты считаешь нужным, именовать во множественном числе или единственном. 

У тебя сейчас `contollers`, но `exception`, `service`

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Очень странный `code style`. Отступы конечно нужны и важны но не после каждой строки же! ))

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
Я начал с пом файла, и видел там подключённую валидацию...
Почему же ты проверяешь длину строку вручную?
Додави валидацию, не ленись, просмотри все доступные кейсы.

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new NoSuchItemException("Id не соответствует требованиям!");
В таком контексте это не правильный запрос. 
Ты проверил что тебе прислали неверный id.
Поэтому надо ответить клиенту 400 а не 404

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if(!StringUtils.hasText(user.getName())) {
`+ в карму` за то что используешь `StringUtils` мало кто вообще про них знает!

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoSuchItemException.java
> +public class NoSuchItemException extends RuntimeException {
Вообще, классы ошибок в веб сервисах именую согласно названиям из `HttpStatus`.
Т.е. не `NoSuchItemException`, а `NotFoundException`

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Соответственно `BadRequestException`

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
А вот тут наоборот не хватает отступов между полями, всё сливается и становится абсолютно не читаемым.

2022-09-18 20:53 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я буду топить за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml` -> `application.yml`

Соответственно - попрошу тебя этому следовать.

Как мини задание: разберись как задать порт для сервиса отличный от дефолтного, и как задать чтобы порт был случайным.
`Менять порт на другой не нужно, для тестов нужен именно 8080`

2022-09-20 17:30 UTC, Kirill-Prokhorov commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Почитал. Как я понимаю первая версия будет 0.1.0 Исправил пока на такую.

2022-09-20 17:30 UTC, Kirill-Prokhorov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +package ru.yandex.practicum.filmorate.controllers;
Принял

2022-09-20 17:33 UTC, Kirill-Prokhorov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Честно говоря, мне глаз режет если сливаются переменные и начало ветвления, или когда какие то методы вызываются сразу за фигурной скобкой. Я стараюсь с ними не перебарщивать.

2022-09-20 17:34 UTC, Kirill-Prokhorov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
Не заметил @Size =/ Спасибо =)

2022-09-20 17:53 UTC, Kirill-Prokhorov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new NoSuchItemException("Id не соответствует требованиям!");
На 400 ответы ругались тесты в Postman. Я еще раз осмотрел код и решил что этот блок в общем и не нужен.

2022-09-20 17:53 UTC, Kirill-Prokhorov commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoSuchItemException.java
> +public class NoSuchItemException extends RuntimeException {
Принял

2022-09-20 18:00 UTC, Kirill-Prokhorov commented on src/main/resources/application.properties
> +
Насколько я понял случайный порт  задается server.port = 0

2022-09-20 19:04 UTC, fizanatic commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Да, даже в пре-продакшн мы еще не вышли.
Но, кстати, никто не запрещает добавлять постфиксы типа: `alpha`, `beta`

2022-09-20 19:06 UTC, fizanatic commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
В целом пиши пока как тебе удобно... но у меня опыта побольше, если прям сильно будет резать мой глаз я напишу тебе )

2022-09-20 19:10 UTC, fizanatic approved these changes

2022-09-20 19:19 UTC, Kirill-Prokhorov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Договорились. Вообще буду рад любой критике.

2022-09-20 19:20 UTC, Kirill-Prokhorov commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Как я из статьи понял постфиксы пишутся на предрелизе. Я думал добавить, но показалось что рано.

2022-09-20 19:23 UTC, merged